//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliasApiWebRef.AliasApi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AliasApiWebRef.AliasApi.AliasApiSoap")]
    public interface AliasApiSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AliasCreate", ReplyAction="*")]
        System.Threading.Tasks.Task<AliasApiWebRef.AliasApi.AliasCreateResponse> AliasCreateAsync(AliasApiWebRef.AliasApi.AliasCreateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AliasCreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AliasCreate", Namespace="http://tempuri.org/", Order=0)]
        public AliasApiWebRef.AliasApi.AliasCreateRequestBody Body;
        
        public AliasCreateRequest()
        {
        }
        
        public AliasCreateRequest(AliasApiWebRef.AliasApi.AliasCreateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AliasCreateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmldata;
        
        public AliasCreateRequestBody()
        {
        }
        
        public AliasCreateRequestBody(string xmldata)
        {
            this.xmldata = xmldata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AliasCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AliasCreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public AliasApiWebRef.AliasApi.AliasCreateResponseBody Body;
        
        public AliasCreateResponse()
        {
        }
        
        public AliasCreateResponse(AliasApiWebRef.AliasApi.AliasCreateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AliasCreateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AliasCreateResult;
        
        public AliasCreateResponseBody()
        {
        }
        
        public AliasCreateResponseBody(string AliasCreateResult)
        {
            this.AliasCreateResult = AliasCreateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface AliasApiSoapChannel : AliasApiWebRef.AliasApi.AliasApiSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AliasApiSoapClient : System.ServiceModel.ClientBase<AliasApiWebRef.AliasApi.AliasApiSoap>, AliasApiWebRef.AliasApi.AliasApiSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AliasApiSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AliasApiSoapClient.GetBindingForEndpoint(endpointConfiguration), AliasApiSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AliasApiSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AliasApiSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AliasApiSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AliasApiSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AliasApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AliasApiWebRef.AliasApi.AliasCreateResponse> AliasApiWebRef.AliasApi.AliasApiSoap.AliasCreateAsync(AliasApiWebRef.AliasApi.AliasCreateRequest request)
        {
            return base.Channel.AliasCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AliasApiWebRef.AliasApi.AliasCreateResponse> AliasCreateAsync(string xmldata)
        {
            AliasApiWebRef.AliasApi.AliasCreateRequest inValue = new AliasApiWebRef.AliasApi.AliasCreateRequest();
            inValue.Body = new AliasApiWebRef.AliasApi.AliasCreateRequestBody();
            inValue.Body.xmldata = xmldata;
            return ((AliasApiWebRef.AliasApi.AliasApiSoap)(this)).AliasCreateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AliasApiSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AliasApiSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AliasApiSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://domino-dpf-api/AliasApi.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AliasApiSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://domino-dpf-api/AliasApi.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AliasApiSoap,
            
            AliasApiSoap12,
        }
    }
}
