//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AmResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AmResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCM.Resources.AmResource", typeof(AmResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind nicht berechtigt eine Statusänderung zu autorisieren!.
        /// </summary>
        public static string Alias_Message_NoRightsToAuthorize {
            get {
                return ResourceManager.GetString("Alias_Message_NoRightsToAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktiviert.
        /// </summary>
        public static string Alias_Status_Active {
            get {
                return ResourceManager.GetString("Alias_Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gelöscht.
        /// </summary>
        public static string Alias_Status_Deleted {
            get {
                return ResourceManager.GetString("Alias_Status_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deaktiviert.
        /// </summary>
        public static string Alias_Status_Inactive {
            get {
                return ResourceManager.GetString("Alias_Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle.
        /// </summary>
        public static string Alias_Status_SelectAll {
            get {
                return ResourceManager.GetString("Alias_Status_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Begründung.
        /// </summary>
        public static string AliasDetail_ActionReason {
            get {
                return ResourceManager.GetString("AliasDetail_ActionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genehmigen.
        /// </summary>
        public static string AliasDetail_Btn_Authorize {
            get {
                return ResourceManager.GetString("AliasDetail_Btn_Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ablehnen.
        /// </summary>
        public static string AliasDetail_Btn_Cancel {
            get {
                return ResourceManager.GetString("AliasDetail_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivieren.
        /// </summary>
        public static string AliasDetail_Btn_Deactivate {
            get {
                return ResourceManager.GetString("AliasDetail_Btn_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string AliasDetail_Btn_Delete {
            get {
                return ResourceManager.GetString("AliasDetail_Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaktivieren.
        /// </summary>
        public static string AliasDetail_Btn_Reactivate {
            get {
                return ResourceManager.GetString("AliasDetail_Btn_Reactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias Eintrag.
        /// </summary>
        public static string AliasDetail_Header {
            get {
                return ResourceManager.GetString("AliasDetail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias Aktion Historie.
        /// </summary>
        public static string AliasDetail_History_Header {
            get {
                return ResourceManager.GetString("AliasDetail_History_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt bisher.
        /// </summary>
        public static string AliasFilter_AllTime {
            get {
                return ResourceManager.GetString("AliasFilter_AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigen.
        /// </summary>
        public static string AliasFilter_Btn_Submit {
            get {
                return ResourceManager.GetString("AliasFilter_Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtereinstellungen.
        /// </summary>
        public static string AliasFilter_CardTitle {
            get {
                return ResourceManager.GetString("AliasFilter_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von.
        /// </summary>
        public static string AliasFilter_From {
            get {
                return ResourceManager.GetString("AliasFilter_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liz-ID.
        /// </summary>
        public static string AliasFilter_License {
            get {
                return ResourceManager.GetString("AliasFilter_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle.
        /// </summary>
        public static string AliasFilter_License_SelectAll {
            get {
                return ResourceManager.GetString("AliasFilter_License_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to übergreifend.
        /// </summary>
        public static string AliasFilter_License_Uebergreifend {
            get {
                return ResourceManager.GetString("AliasFilter_License_Uebergreifend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AliasFilter_Name {
            get {
                return ResourceManager.GetString("AliasFilter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AliasFilter_Status {
            get {
                return ResourceManager.GetString("AliasFilter_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straße.
        /// </summary>
        public static string AliasFilter_Street {
            get {
                return ResourceManager.GetString("AliasFilter_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bis.
        /// </summary>
        public static string AliasFilter_To {
            get {
                return ResourceManager.GetString("AliasFilter_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erwartet Autorisierung.
        /// </summary>
        public static string AliasFilter_WaitAuth {
            get {
                return ResourceManager.GetString("AliasFilter_WaitAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias Info.
        /// </summary>
        public static string AliasInfo_Dialog_Header {
            get {
                return ResourceManager.GetString("AliasInfo_Dialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AliasInfo_Tab0_Header {
            get {
                return ResourceManager.GetString("AliasInfo_Tab0_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historie.
        /// </summary>
        public static string AliasInfo_Tab1_Header {
            get {
                return ResourceManager.GetString("AliasInfo_Tab1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias Liste.
        /// </summary>
        public static string AliasList_Content_CardTitle {
            get {
                return ResourceManager.GetString("AliasList_Content_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Beleg Nr..
        /// </summary>
        public static string AliasList_Content_Column_BelegNr {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_BelegNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCM Case-ID.
        /// </summary>
        public static string AliasList_Content_Column_CaseId {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_CaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch.
        /// </summary>
        public static string AliasList_Content_Column_CreatedBy {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingerichtet.
        /// </summary>
        public static string AliasList_Content_Column_CreatedOn {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCM Profil.
        /// </summary>
        public static string AliasList_Content_Column_HCMProfile {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_HCMProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string AliasList_Content_Column_Id {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liz-ID.
        /// </summary>
        public static string AliasList_Content_Column_LicName {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_LicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AliasList_Content_Column_Name {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AliasList_Content_Column_Status {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straße.
        /// </summary>
        public static string AliasList_Content_Column_Street {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erwartet Autorisierung.
        /// </summary>
        public static string AliasList_Content_Column_Wait4Auth {
            get {
                return ResourceManager.GetString("AliasList_Content_Column_Wait4Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivierung.
        /// </summary>
        public static string AliasProtocol_Action_Deactivation {
            get {
                return ResourceManager.GetString("AliasProtocol_Action_Deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschung.
        /// </summary>
        public static string AliasProtocol_Action_Delete {
            get {
                return ResourceManager.GetString("AliasProtocol_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einrichtung.
        /// </summary>
        public static string AliasProtocol_Action_Insert {
            get {
                return ResourceManager.GetString("AliasProtocol_Action_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaktivierung.
        /// </summary>
        public static string AliasProtocol_Action_Reactivation {
            get {
                return ResourceManager.GetString("AliasProtocol_Action_Reactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion.
        /// </summary>
        public static string AliasProtocol_Column_Action {
            get {
                return ResourceManager.GetString("AliasProtocol_Column_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genehmigungsnotiz.
        /// </summary>
        public static string AliasProtocol_Column_AuthNote {
            get {
                return ResourceManager.GetString("AliasProtocol_Column_AuthNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorisiert durch.
        /// </summary>
        public static string AliasProtocol_Column_AuthorizedBy {
            get {
                return ResourceManager.GetString("AliasProtocol_Column_AuthorizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string AliasProtocol_Column_Date {
            get {
                return ResourceManager.GetString("AliasProtocol_Column_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angefordert durch.
        /// </summary>
        public static string AliasProtocol_Column_RequestedBy {
            get {
                return ResourceManager.GetString("AliasProtocol_Column_RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begründung.
        /// </summary>
        public static string AliasProtocol_Column_RequestReason {
            get {
                return ResourceManager.GetString("AliasProtocol_Column_RequestReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AliasProtocol_Column_Status {
            get {
                return ResourceManager.GetString("AliasProtocol_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorisiert.
        /// </summary>
        public static string AliasProtocol_Status_Authorized {
            get {
                return ResourceManager.GetString("AliasProtocol_Status_Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgelehnt.
        /// </summary>
        public static string AliasProtocol_Status_Discarded {
            get {
                return ResourceManager.GetString("AliasProtocol_Status_Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erwartet Autorisierung.
        /// </summary>
        public static string AliasProtocol_Status_Waiting {
            get {
                return ResourceManager.GetString("AliasProtocol_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias Bericht.
        /// </summary>
        public static string AliasReport_Content_CardTitle {
            get {
                return ResourceManager.GetString("AliasReport_Content_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzeptiert.
        /// </summary>
        public static string AliasReport_Content_Column_Accepted {
            get {
                return ResourceManager.GetString("AliasReport_Content_Column_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoriert.
        /// </summary>
        public static string AliasReport_Content_Column_Ignored {
            get {
                return ResourceManager.GetString("AliasReport_Content_Column_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden ....
        /// </summary>
        public static string Component_Status_Loading {
            get {
                return ResourceManager.GetString("Component_Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden fehlgeschlagen ....
        /// </summary>
        public static string Component_Status_LoadingFailed {
            get {
                return ResourceManager.GetString("Component_Status_LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Daten gefunden.
        /// </summary>
        public static string Component_Status_NoData {
            get {
                return ResourceManager.GetString("Component_Status_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion fehlgeschlagen!.
        /// </summary>
        public static string Form_Action_Error {
            get {
                return ResourceManager.GetString("Form_Action_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Form_Button_Cancel {
            get {
                return ResourceManager.GetString("Form_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string Form_Button_Close {
            get {
                return ResourceManager.GetString("Form_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Form_Button_Delete {
            get {
                return ResourceManager.GetString("Form_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string Form_Button_No {
            get {
                return ResourceManager.GetString("Form_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Form_Button_OK {
            get {
                return ResourceManager.GetString("Form_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Form_Button_Reset {
            get {
                return ResourceManager.GetString("Form_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Form_Button_Save {
            get {
                return ResourceManager.GetString("Form_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Form_Button_Yes {
            get {
                return ResourceManager.GetString("Form_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Löschen ist ein Fehler aufgetreten ! .
        /// </summary>
        public static string Form_Delete_Error {
            get {
                return ResourceManager.GetString("Form_Delete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschung erfolgreich abgeschlossen !.
        /// </summary>
        public static string Form_Delete_Success {
            get {
                return ResourceManager.GetString("Form_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte auswählen.
        /// </summary>
        public static string Form_Field_DropDown_PlaceHolder {
            get {
                return ResourceManager.GetString("Form_Field_DropDown_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; darf einen Wert zwischen {1} und {2} haben.
        /// </summary>
        public static string Form_Field_Range {
            get {
                return ResourceManager.GetString("Form_Field_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; hat ungültigen Zeichen !.
        /// </summary>
        public static string Form_Field_RegularExpression {
            get {
                return ResourceManager.GetString("Form_Field_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; ist ein Pflichtfeld !.
        /// </summary>
        public static string Form_Field_Required {
            get {
                return ResourceManager.GetString("Form_Field_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; muss eine Länge zwischen {2} und {1} Zeichen haben..
        /// </summary>
        public static string Form_Field_StringLength {
            get {
                return ResourceManager.GetString("Form_Field_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern !.
        /// </summary>
        public static string Form_Saved_Error {
            get {
                return ResourceManager.GetString("Form_Saved_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherung erfolgreich abgeschlossen !.
        /// </summary>
        public static string Form_Saved_Success {
            get {
                return ResourceManager.GetString("Form_Saved_Success", resourceCulture);
            }
        }
    }
}
